version: '3.8'

services:
  # Zookeeper for Kafka coordination
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka message broker
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # PostgreSQL database for Hasura
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hasura_db
      POSTGRES_USER: hasurauser
      POSTGRES_PASSWORD: hasurapassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Hasura GraphQL Engine
  hasura:
    image: hasura/graphql-engine:v2.0.0
    container_name: hasura
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasurauser:hasurapassword@postgres:5432/hasura_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_DEV_MODE: "true"

  # Flask Producer service
  producer:
    build: ./producer
    container_name: flask_producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:29092
    ports:
      - "5000:5000"

  # Flask Consumer service
  consumer:
    build: ./consumer
    container_name: flask_consumer
    depends_on:
      - kafka
      - postgres
    environment:
      KAFKA_BROKER: kafka:29092
      POSTGRES_HOST: postgres
      POSTGRES_USER: hasurauser
      POSTGRES_PASSWORD: hasurapassword
      POSTGRES_DB: hasura_db

volumes:
  postgres-data: